language: objective-c
osx_image: xcode7.1

before_install:
  - gem install xcpretty
  - brew update || brew update # temporary workaround
  - brew install carthage

script:
  - rake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
